
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AccountType = {
  OAUTH: 'OAUTH',
  CREDENTIALS: 'CREDENTIALS'
} as const

export type AccountType = (typeof AccountType)[keyof typeof AccountType]


export const TokenType = {
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  TWO_FACTOR_AUTH: 'TWO_FACTOR_AUTH'
} as const

export type TokenType = (typeof TokenType)[keyof typeof TokenType]


export const Roles = {
  USER: 'USER',
  ADMIN: 'ADMIN'
} as const

export type Roles = (typeof Roles)[keyof typeof Roles]
